name: CI/CD Pipeline for Supervised Learning Model

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run model training and testing
      - name: Run model training and testing
        run: |
          python src/model.py

      # Step 5: Upload trained model as an artifact
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: model.pkl

  deploy-to-databricks:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download trained model
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: .

      # Step 3: Deploy to Databricks
      - name: Deploy to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_USERNAME: ${{ secrets.DATABRICKS_USERNAME }}
          DATABRICKS_PASSWORD: ${{ secrets.DATABRICKS_PASSWORD }}
        run: |
          pip install databricks-cli
          python deploy.py
